### ISSUE TITLE
Enforcement of strategy exposure limits may be incorrect

### ISSUE THREAD

**Issue by doovd** [liampauling/flumine#163]
If we use the following scenario:
* Set max_selection_exposure as 2.
* Back selection A at odds of 5, with a stake of £2.
* This order goes through as it is within the limits.
* Then, lay the selection at odds of 1.5 with a stake of £2. Liability here is £1.
* StrategyExposure then does the following computation:

```
exposure = (order.order_type.price - 1) * order.order_type.size 
#correct (computed as 1)

current_selection_exposure = market.blotter.selection_exposure( strategy, lookup=order.lookup)
#current_selection_exposure is computed as -2 due to the original back bet.

if (current_selection_exposure - exposure) < -strategy.max_selection_exposure:
    self._on_error(order)
#This is computed as If -2 -1 < -2: self._on_error(order)
```

In this case, the lay would have been rejected, despite being risk-reducing. Perhaps it would make it easier if "back" exposure was tracked as a positive value, and lay exposure tracked as a negative value (as one would do if they were buying/selling).

**Comment by liampauling** [comment]
Gone down the positive route, are you able to test this on your example?

https://github.com/liampauling/flumine/pull/174
