### ISSUE TITLE
Add hedging/take-profit/stop loss functionality

### ISSUE THREAD

**Issue by jcussen** [liampauling/flumine#267]
Allow each complete order to have an adjustable take-profit price and/or stop loss price so it can be framed within a trading range. Currently possible solution is by using multiple strategies.

**Comment by liampauling** [comment]
To think about:

-         time: float (seconds)
-         price: float
-         profit: float
-         reverse: bool
-         green: bool (green or just offset with same amount)
-         time_in_force: bool
-         persist: bool
-         fill_kill_time: float

**Comment by varneyo** [comment]
My thoughts on this, and the more I developed my personal hedging I am thinking it is going be very hard to achieve something that is going to suits a general requirements. Weak markets / bad positions with a generalised hedge function, will only lead to frustration and asking for a more specific hedging. 

Stop loss assumes volume is available which is another big issue and again people will complain probably when they get hit for more then the stop loss. 

If there was going to be a hedging function I would keep it simple and just allow for it to be called X seconds to off, to fully green up and spread the profit across all selections. It should be done on the trade level for sure to keep things simple again. 

Id say that if was going to be done properly then it would require some form of larger hedging class, but again after a few weeks of thought I now am in the camp of leave it to the user unless the function is simple and quite restrictive in nature.

**Comment by jsphon** [comment]
As a precursor to this, would it be a good idea to implement flumine.order.trade.Trade.offset_orders first?

This issue will probably need to use offset_orders. And implementing offset_orders could help us learn more about, and understand, potential problems that may arise. For one, I don't think Betfair has stop loss orders.
