### ISSUE TITLE
Allow different separators in customer_order_ref.

### ISSUE THREAD

**Issue by jsphon** [liampauling/flumine#287]
Change

```
def customer_order_ref(self) -> str:
    return "{0}-{1}".format(self.trade.strategy.name_hash, self.id)
```
to:

```
def customer_order_ref(self) -> str:
    return "{0}{1}{2}".format(self.trade.strategy.name_hash, self.sep, self.id)
```

, where `self.sep` defaults to `'-'`

**Comment by liampauling** [comment]
Validation on type and length on `init`?

**Comment by jsphon** [comment]
> Validation on type and length on `init`?

I'll set it to length 1, and conform to allowed characters specified in here:

https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/placeOrders
