### ISSUE TITLE
limit order with market on close persistence type get filled even when exposure is less than £10.

### ISSUE THREAD

**Issue by dandan2002** [liampauling/flumine#320]

**Comment by liampauling** [comment]
Does it error on the request or lapse when the market turns inplay?

From memory this only required for lay bets or is it both?

**Comment by dandan2002** [comment]
In live, it showd order lapsed. It is a limit order with market on close persistence. I need to look for details in betfair about the rule on this.

**Comment by dandan2002** [comment]
Can I request to ‘Take SP’ on an unmatched lay bet if my liability is less than £10? (Minimum liability)
Yes, but at the off if the liability on the bet is less than £10 the bet will be cancelled and will not be included in the SP reconciliation.
For example:  As an Exchange layer I decide to lay a horse for £5 @ 2.0. It is trading at 3.0 so my bet is unmatched. I then request to ‘Take SP’ at the off if my bet is still unmatched at 2.0. The system will allow this request but if unmatched at the off it will lapse.  Also, if a customer for example asks to lay £50 at 1.5, convert to SP if unmatched, and £40 gets taken leaving £10 lay at 1.5 the balance will cancel at the off. It will not convert into an SP lay bet as the revised balance at the off was less than the minimum £10 liability allowed for SP bets.

**Comment by liampauling** [comment]
Great, and back bets work fine?

**Comment by dandan2002** [comment]
No. Backtest still shows the ordered matched.

**Comment by liampauling** [comment]
I mean live, I was under the impression back limit orders will still enter the auction even if its below the min bet size

**Comment by dandan2002** [comment]
I don’t know about back bet but from the betfair q and a it seems the £10 exposure rule covers both back and lay orders.

**Comment by dandan2002** [comment]
Is it possible to check with betfair about back bet rule?

**Comment by liampauling** [comment]
Works fine with back bets

![Screenshot 2020-11-11 at 11 31 38](https://user-images.githubusercontent.com/12016537/98806712-82a7a180-2411-11eb-878f-cf7c567b9a13.png)

**Comment by dandan2002** [comment]
Ok Thanks.good to know.
