### ISSUE TITLE
Adjustment Factor Bug

### ISSUE THREAD

**Issue by jsphon** [liampauling/flumine#347]
If I was matched at decimal odds of 3.2, and the adjustment factor was 75.18, what should the new price be?
From reading this document, I also get 0.79. But how is it possible to get matched at 0.79? 1.01 is the lowest possible odds.
10:01

https://en-betfair.custhelp.com/app/answers/detail/a_id/408/~/exchange%3A-in-a-horse-race%2C-how-will-non-runners-be-treated%3F

The adjustment factor code is here:
https://github.com/liampauling/flumine/blob/4f08f389a3c5c2722b60252055b143cfdfefb0f7/flumine/markets/middleware.py#L104-L107

**Comment by liampauling** [comment]
Bugfix in #348 agree?

**Comment by jsphon** [comment]
Thanks Liam. I'm not sure exactly what the rules are in this scenario. But the bugfix is definitely better than the current implementation. I'll send an email to BDP to get confirmation.

**Comment by liampauling** [comment]
From my experience it will default to 1.01 (never lower) as you do sometimes see this.
