### ISSUE TITLE
Small replacement orders fail due to size violation.

### ISSUE THREAD

**Issue by new-to-python99** [liampauling/flumine#366]
When a new order is created, the default behaviour is for Flumine to validate against the minimum bet size of (varying by location, but GBP 2.00 stake or GBP 10.00 exposure in the UK). 

This functions correctly, however when replacing an order, this validation should not occur, as it should be possible to amend the price for the remaining portion of an existing order, currently this returns a Violation, whereas in the GUI and via the REST API it is possible to change the price on these small sizes.

**Comment by liampauling** [comment]
Quick fix will be to only enable the min_bet_size validation when the OrderPackage is a place, minor refactor.

**Comment by liampauling** [comment]
Do you have logs for this? 

The control only checks the original size/price so a replace below minimum will not cause a violation, just checked on my side and it works as expected.

**Comment by new-to-python99** [comment]
Here is the log:

https://betfairlightweight.slack.com/archives/C4H05ML2E/p1610403796071400

When I set:

client.min_bet_validation = False

and handle the logic elsewhere it works fine, so it definitely appears to be that causing the error.
