### ISSUE TITLE
Order produces a Strategy Exposure violation on replace

### ISSUE THREAD

**Issue by new-to-python99** [liampauling/flumine#382]
As of flumine 1.17.x when replacing an order it incorrectly returns a violation for the newly replaced order.

Example log of erroneous behaviour:

https://betfairlightweight.slack.com/archives/C4H05ML2E/p1614359705072200

The expected behaviour (for replacing an order) is that there is no violation as there are not two simultaneous orders, 1 having  been cancelled before the new one is placed.

**Comment by liampauling** [comment]
fixed in 1.17.5
