### ISSUE TITLE
Orders not cancellable when transaction limit is reached

### ISSUE THREAD

**Issue by flxbe** [liampauling/flumine#452]
Hi Liam

When using the `MaxTransactionCount` validator, I am not able to cancel executable orders as soon as the transaction limit is reached. Also, the order now has the status `violated`, although it is in fact still executable.

I can see multiple possible changes to solve this problem:

1. Introduce a `force` parameter to `market.place_order`, `market.cancel_order`, etc. If `force == True`, then the validation is skipped.
2. Make `MaxTransactionCount` aware of the actual operation:
2.1. Either: Set order to `executable` instead of `violated` if the operation is changing an existing operation instead of placing a new one.
2.2. Or: Just skip the validation for operations that change an existing order.

The change 2.1. would only prevent the wrong status change, but still does not allow to actually cancel the order. I personally prefer the first solution, as it allows every strategy to define the behavior suitable for the specific use case. Also, this would be a non-breaking change. I would be happy to implement the change as soon as the next steps are clear. Please let me know what you think.

**Comment by liampauling** [comment]
Force sounds good, I assume this would skip all trading/client controls when True?

Regardless you are correct as the order shouldn't be violated if a cancel fails.

**Comment by flxbe** [comment]
> Force sounds good, I assume this would skip all trading/client controls when True?

Yes.

I will create a first draft of the change and come back to you with the PR.
