### ISSUE TITLE
Replace Orders drop custom separator from order_id field (for simulated order execution)

### ISSUE THREAD

**Issue by new-to-python99** [liampauling/flumine#453]
When a new order is placed, it is possible to customise the separation character, using the 'sep' parameter, however when an order is replaced (in simulation mode, i.e. backtesting or paper trading) the replacement order_id drops the customised separator and replaces it with the default '-'.

This doesn't appear to affect live orders, only simulated ones.

**Comment by new-to-python99** [comment]
Actually, I think this might affect live too (but again only for replacement orders, it works fine on new orders).

**Comment by liampauling** [comment]
You are right, impacts live and simulated on replace orders, fix now in
