### ISSUE TITLE
Add matched bets to runner_context 

### ISSUE THREAD

**Issue by OzMcGoo** [liampauling/flumine#472]
As per discussion on Slack channel.Please can we add matched bets to the runner_context so as to track the number of matched bets per runner(Horse Racing in this case but useful otherwise).Thank you

**Comment by liampauling** [comment]
By bets do you mean orders? And by matched do you include partial?

**Comment by OzMcGoo** [comment]
> By bets do you mean orders? And by matched do you include partial?

Yes orders and yes partial included.Thanks

**Comment by liampauling** [comment]
Keeping `RunnerContext` as is and refactoring the blotter so this data is more easily accessable / the golden source for orders, for example:

```python
market.blotter.strategy_selection_orders(self, 39641069)
market.blotter.strategy_selection_orders(self, 39641069, order_status=OrderStatus.EXECUTABLE)
market.blotter.strategy_selection_orders(self, 39641069, matched_only=True)
```

In your case you would do this:

```python
len(market.blotter.strategy_selection_orders(self, 39641069, matched_only=True))
```

or this if you only wanted execution complete matched orders:

```python
len(market.blotter.strategy_selection_orders(self, 39641069,  order_status=OrderStatus.EXECUTION_COMPLETE, matched_only=True))
```
