### ISSUE TITLE
Runner total.matched is incorrect when stream is historical data.

### ISSUE THREAD

**Issue by ThomasAJ05** [liampauling/flumine#476]
According to Betfair Developers  FAQ, in historical data, the runner tv (“tv”) represents the cumulative traded amount at the last price traded (ltp) or cumulative amount of all ‘trd’ amounts in the update if multiple prices are included.

The code "runner.total_matched = new_data["tv"] in BFLW  Class MarketBookCache > def update_cache" therefore does not end up storing a runner's **total** traded volume.

Currently this affects this Flume code "class RunnerAnalytics > def _calculate_matched". The code returns round(total_matched - prev_total_matched, 2) seems to assume that total_matched is always increasing in value when it's not. Numerous times the returned value is a negative (and by large amounts as I recorded them) which is not possible in real life."

**Comment by liampauling** [comment]
Now fixed in version 1.19.9

```python
strategy = LowestLayer(
    market_filter={"markets": markets, "listener_kwargs": {"cumulative_runner_tv": True}},
    max_order_exposure=1000,
    max_selection_exposure=105,
    context={"stake": 2},
)
```
