### ISSUE TITLE
UML diagrams for documentation

### ISSUE THREAD

**Issue by shashikhaya** [liampauling/flumine#525]
I have created UML diagrams for the package using pyreverse:

Packages
![packages_flumine](https://user-images.githubusercontent.com/79042680/141372198-24ae4df4-0fe8-4554-abef-a70cf58af75e.png)

Classes
![classes_flumine](https://user-images.githubusercontent.com/79042680/141372312-1a01735f-34c1-4c91-b904-0b05fa46629d.png)

Hopefully this is useful - it helped me to understand the package

**Comment by ThomasAJ05** [comment]
Thanks shashikhaya

Now I have to learn how to read it.
Hm... might get the images printed on a sign writer's printer and cover my walls.  hahaha
