### ISSUE TITLE
MarketOnCloseOrders not included in BacktestLoggingControl example

### ISSUE THREAD

**Issue by demhadbale** [liampauling/flumine#528]
MarketOnCloseOrders not included in out of the box BacktestLoggingControl example (https://github.com/liampauling/flumine/blob/master/examples/controls/backtestloggingcontrol.py). Using in live framework. Only changed order.txt path.

`import csv
import logging
from flumine.controls.loggingcontrols import LoggingControl

logger = logging.getLogger(__name__)

FIELDNAMES = [
    "bet_id",
    "strategy_name",
    "market_id",
    "selection_id",
    "trade_id",
    "date_time_placed",
    "price",
    "price_matched",
    "size",
    "size_matched",
    "status",
    "side",
    "elapsed_seconds_executable",
    "order_status",
    "market_note",
    "trade_notes",
    "order_notes",
]

class StrategyLoggingControl(LoggingControl):
    NAME = "STRATEGY_LOGGING_CONTROL"

    def __init__(self, *args, **kwargs):
        super(StrategyLoggingControl, self).__init__(*args, **kwargs)
        self._setup()

    def _setup(self):
        with open("C:/Users/Administrator/AppData/Local/Programs/Python/Python39/Lib/site-packages/flumine/strategies/orders.txt", "w") as m:
            csv_writer = csv.DictWriter(m, delimiter=",", fieldnames=FIELDNAMES)
            csv_writer.writeheader()

    def _process_cleared_orders_meta(self, event):
        orders = event.event
        with open("C:/Users/Administrator/AppData/Local/Programs/Python/Python39/Lib/site-packages/flumine/strategies/orders.txt", "a") as m:
            for order in orders:
                try:
                    order_data = {
                        "bet_id": order.bet_id,
                        "strategy_name": order.trade.strategy,
                        "market_id": order.market_id,
                        "selection_id": order.selection_id,
                        "trade_id": order.trade.id,
                        "date_time_placed": order.responses.date_time_placed,
                        "price": order.order_type.price,
                        "price_matched": order.average_price_matched,
                        "size": order.order_type.size,
                        "size_matched": order.size_matched,
                        "status": order.runner_status,
                        "side": order.side,
                        "elapsed_seconds_executable": order.elapsed_seconds_executable,
                        "order_status": order.status.value,
                        "market_note": order.trade.market_notes,
                        "trade_notes": order.trade.notes_str,
                        "order_notes": order.notes_str,
                    }
                    csv_writer = csv.DictWriter(m, delimiter=",", fieldnames=FIELDNAMES)
                    csv_writer.writerow(order_data)
                except Exception as e:
                    logger.error(
                        "_process_cleared_orders_meta: %s" % e,
                        extra={"order": order, "error": e},
                    )

        logger.info("Orders updated", extra={"order_count": len(orders)})

    def _process_cleared_markets(self, event):
        cleared_markets = event.event
        for cleared_market in cleared_markets.orders:
            logger.info(
                "Cleared market",
                extra={
                    "market_id": cleared_market.market_id,
                    "bet_count": cleared_market.bet_count,
                    "profit": cleared_market.profit,
                    "commission": cleared_market.commission,
                },
            )
`

**Comment by demhadbale** [comment]
So it seems MarketOnCloseOrders aren't being cleared properly on flumine because no price

{"asctime": "2021-11-23 06:57:50,183", "levelname": "ERROR", "message": "_process_cleared_orders_meta: 'MarketOnCloseOrder' object has no attribute 'price'", "order": "Order 251408671038: Execution complete", "error": "'MarketOnCloseOrder' object has no attribute 'price'"}

Maybe this is why they aren't making it to the logging control?

**Comment by liampauling** [comment]
Ah good spot, that would be why
