### ISSUE TITLE
Backtest: Removed Runners Returning Simulated Profit

### ISSUE THREAD

**Issue by JustinFP** [liampauling/flumine#540]
I am backtesting a strategy using betfair pro data. I have followed the examples and started running backtests but have noticed an issue with simulated profit. Removed runners are returning a simulated profit (please refer to output image below)(Note: this is a backing strategy, it seems odd that the simulation would see a removed runner as winner).
![Capture_Removed_Sel_Profit](https://user-images.githubusercontent.com/38202692/146903191-79351e05-9dfc-4af7-b1ec-3d866dae70ac.JPG)

My backtest code

'''
client = clients.BacktestClient()

framework = FlumineBacktest(client=client)

root_folder = 'C:/BF_PRO_DATA/Nov/'
folders = os.listdir(root_folder) #list of folders
markets = []

for folder in folders:
    folder = os.path.join(root_folder, folder) #dir to open folder in list of folders
    _markets = os.listdir(folder) # list of files inside folder inside list of folders
    _markets = [x for x in _markets if x.endswith('.bz2')] #adds file names to list
    _markets = [os.path.join(folder, x) for x in _markets] #adds file names to a dir string
    markets.extend(_markets) #adds exact dir for each file to market list

spList=[]

class Test1(BaseStrategy):

    def check_market_book(self, market, market_book):
        if (market.seconds_to_start <= 360) and (market_book.status != "CLOSED") and not market_book.inplay and market.market_type == "WIN":
            return True

    def process_market_book(self, market, market_book):
        
        if (ABC):

            for runner in market_book.runners:
                
                runner_context = self.get_runner_context(market.market_id, runner.selection_id, runner.handicap)
                
                back1 = get_price(runner.ex.available_to_back, 0)
                back2 = get_price(runner.ex.available_to_lay, 0)
                
                #exit current selection itteration if back1 = None
                if back1 == None or back2 == None:
                    continue

                
                if (XYZ):
                        
                    trade = Trade(
                        market_id=market_book.market_id, 
                        selection_id=runner.selection_id,
                        handicap=runner.handicap,
                        strategy=self
                    )
                    
                    order = trade.create_order(
                        side= Side, 
                        order_type=LimitOrder(price=back1, size= sizeB1),
                        notes=OrderedDict(market_vol=round(totalVol, 4), sel_volume = selTradedVol, event_details = market_book.market_definition.name, order_num = 1)
                    )
                    
                    market.place_order(order)
                        
    def process_closed_market(self, market, market_book) -> None:

        for runner in market_book.runners:
            spList.append([runner.selection_id, runner.status, runner.sp.actual_sp])

with mock_patch("builtins.open", smart_open.open):
    strategy = Test1(
        market_filter={"markets": markets,"listener_kwargs": {"seconds_to_start": 360}, "market_types":["WIN"]},
        max_trade_count = 4,
        max_live_trade_count = 4,
        max_order_exposure = 10000,
        max_selection_exposure = 20000
    )
    framework.add_strategy(strategy)
    framework.run()

dfList=[]

for market in framework.markets:

    for order in market.blotter:
        dfList.append(
        [
            market.venue,
            market.country_code,
            market.event_name,
            market.market_start_datetime,
            order.market_id,
            order.selection_id,
            order.notes['event_details'],
            order.notes['market_vol'],
            order.notes['sel_volume'],
            order.notes['order_num'],
            order.responses.date_time_placed,
            order.status,
            order.order_type.price,
            order.average_price_matched,
            order.size_matched,
            order.simulated.profit,
        ]
        )

df = pd.DataFrame(dfList, columns = ['market_venue', 'country_code', 'event_name', 'market_start_datetime', 'market_id', 'selection_id', 'event_details', 'market_vol', 'sel_volume', 'order_num', 'time_placed', 'status', 'price', 'average_price_matched', 'size_matched', 'simulated_profit'])
df['weekday'] = df['time_placed'].dt.dayofweek
df['month'] = df['time_placed'].dt.month

#add bsp
df['bsp']=df['selection_id']
df['selection_status'] = df['selection_id']

for L in spList:
    df.loc[df['selection_id'] == L[0], 'bsp'] = L[2]
    df.loc[df['selection_id'] == L[0], 'selection_status'] = L[1]
    '''

**Comment by ThomasAJ05** [comment]
Hi Justin

I'm not Liam but I've been working in this area a lot lately and I have not seen this behavior.

Are you really really really sure that during the various column manipulation that something has not gone adrift? I've been looking very closely at the code you provided but it's tough to come to any definitive conclusions.

**Comment by JustinFP** [comment]
Hi Thomas,

Apologies, found the error, it is in the assembly of the dataframe. It
occurs when adding runner status and bsp from spList.

The spList is created for all runners in def process_closed_market. I have
added status and bsp to df based on selection_id match:

for L in spList:
    df.loc[df['selection_id'] == L[0], 'bsp'] = L[2]
    df.loc[df['selection_id'] == L[0], 'selection_status'] = L[1]

I run the script for one month block of racing data, therefore error occurs
when selection runs more than once for the month. Please see screenshot
attached, runner '25754300'  ran 3 times, the first run it won, this
explains my output of removed runners having simulated_profit.

Thanks for your time,

 Justin

**Comment by ThomasAJ05** [comment]
You're welcome.
PS please don't forget to close the issue.
