### ISSUE TITLE
Betting to target payout resulting in parameter requirement error due to erroneous 'size' requirement

### ISSUE THREAD

**Issue by demhadbale** [liampauling/flumine#541]
"Unknown error __init__() missing 1 required positional argument: 'size' in process_market_book" error resulting from bet_target_type="BACKERS_PROFIT" orders.

order = trade.create_order(
    side="BACK",
    order_type=LimitOrder(price=get_price(runner.ex.available_to_back,0), bet_target_type="BACKERS_PROFIT", bet_target_size=50)
)

**Comment by ThomasAJ05** [comment]
Hi @demhadbale 
I am not familiar with the type of LimitOrder that you are using but in the [Betfair documentation](https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/Betting+Type+Definitions#BettingTypeDefinitions-LimitOrder) please note that 'size' is a required field and therefore the LimitOrder class also has this field as required.

**Comment by demhadbale** [comment]
Hi @ThomasAJ05 

Please refer to https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/placeOrders#placeOrders-BettoPayoutorProfit/Liability where 'size' is not a requirement in the given API call example

**Comment by ThomasAJ05** [comment]
Yes I see that and indeed when I was looking at your original post I thought it was maybe strange. But not having experience in this type of bet I thought 'what do I know. the docs is the docs?'. Might I suggest Betfairlightwight Slack?

**Comment by liampauling** [comment]
Fixed in 1.21.0, note that this will not work when backtesting.
